# Docker Compose file for TurtleBot Behavior Examples
#
# Usage:
#
# To build the images:
#   docker compose build
#
# To start up a specific service by name:
#   docker compose up <service_name>
#
# To open an interactive shell to a running container:
#   docker exec -it <container_name> bash

services:
  # Base image containing dependencies.
  base:
    image: ros2_base:v0.0.1
    container_name: ros2_base
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        ROS_DISTRO: humble
      # no specific build target; Dockerfile isn't multi‑stage with a 'base' stage
      target: base
    # Interactive shell
    stdin_open: true
    tty: true
    # Networking and IPC for ROS 2
    network_mode: host
    ipc: host
    # Needed to display graphical applications
    privileged: True
    runtime: nvidia
    environment:
      # Allows graphical programs in the container.
      - DISPLAY=${DISPLAY:-:1}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_DRIVER_CAPABILITIES=all
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
    volumes:
      # Allows graphical programs in the container.
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTHORITY:-$HOME/.Xauthority}:/root/.Xauthority

    # overlay_1 extends the base image and adds the UR10-specific workspace and arm_api2 packages.
  overlay_1:
    extends: base
    image: overlay_1:v0.0.1
    container_name: overlay_1
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: overlay_1
    volumes:
      - /arm_api_py:/home/$USERNAME/wbk_ur10_ws/src/arm_api_py
      - /tmp/.X11-unix:/tmp/.X11-unix
  
  overlay_2:
    extends: overlay_1
    image: overlay_2:v0.0.1
    container_name: overlay_2
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: overlay_2
      shm_size: '40gb'
    shm_size: '40gb'
    volumes:
      - /vmf:/home/$USERNAME/wbk_ur10_ws/src/vmf
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host
    environment:
      - DISPLAY=:1
    runtime: nvidia