# FROM cuda_126_ros2_base:latest AS overlay_1
FROM cuda_126_ros2_base:latest
ARG USERNAME=USERNAME
ARG USER_UID=1000
ARG USER_GID=$USER_UID
ARG ROS_DISTRO=humble
ENV HOME=/home/${USERNAME}

###########################################
# Overlay Image for Workspace and packages #
###########################################
# prevent any interactive prompts during package operations
ENV DEBIAN_FRONTEND=noninteractive

# Change the default shell to Bash
SHELL [ "/bin/bash" , "-c" ]


 
# Create a workspace and clone relevant repos
RUN source /opt/ros/${ROS_DISTRO}/setup.bash \
    && mkdir -p $HOME/wbk_ur10_ws/src

WORKDIR $HOME/wbk_ur10_ws/src
COPY ./arm_api2/ ./src/arm_api2
COPY ./arm_api2_msgs/ ./src/arm_api2_msgs
COPY ./arm_api2_py/ ./src/arm_api2_py
COPY ./camera_perception/ ./src/camera_perception

# COPY dependencies.repos .
# RUN vcs import < dependencies.repos
# RUN git clone main git@gitlab.kit.edu:unvug/arm_api2_py.git \
#     && git clone git@gitlab.kit.edu:kit/ifl/gruppen/air/ros2/arm_api2.git \
#     && git clone git@gitlab.kit.edu:kit/ifl/gruppen/air/ros2/arm_api2_msgs.git \
#     && apt-get install python3-colcon-common-extensions -y

WORKDIR $HOME/wbk_ur10_ws
RUN apt-get update -y \
    && rosdep update \
    && rosdep install --from-paths src --ignore-src --rosdistro ${ROS_DISTRO} -y \
    && colcon build --symlink-install

RUN echo "source /opt/ros/${ROS_DISTRO}/setup.bash" >> /home/$USERNAME/.bashrc 

COPY ./docker/entrypoint.sh /
ENTRYPOINT [ "/entrypoint.sh" ]
 
# Set the working folder at startup
WORKDIR $HOME/wbk_ur10_ws