FROM nvidia_ros:latest
ARG USERNAME=USERNAME
ARG USER_UID=1000
ARG USER_GID=$USER_UID
ENV HOME=/home/${USERNAME}

# Change the default shell to Bash
SHELL [ "/bin/bash" , "-c" ]
 
# Install Git
RUN apt-get update && apt-get install -y --no-install-recommends \ 
    git \
    ros-humble-cartographer \
    ros-humble-cartographer-ros \
    ros-humble-navigation2 \
    ros-humble-nav2-bringup
 
# Create a workspace and clone TurtleBot3 repos
RUN source /opt/ros/humble/setup.bash \
    && mkdir -p $HOME/turtlebot3_ws/src \
    && cd $HOME/turtlebot3_ws/src \
    && git clone -b humble https://github.com/ROBOTIS-GIT/DynamixelSDK.git \
    && git clone -b humble https://github.com/ROBOTIS-GIT/turtlebot3_msgs.git \
    && git clone -b humble https://github.com/ROBOTIS-GIT/turtlebot3.git \
    && sudo apt install python3-colcon-common-extensions \
    && cd $HOME/turtlebot3_ws \
    && colcon build --symlink-install 

RUN echo "source /opt/ros/humble/setup.bash" >> /home/$USERNAME/.bashrc \
    && echo "source /usr/share/gazebo/setup.sh" >> /home/$USERNAME/.bashrc \
    && echo "source ~/turtlebot3_ws/install/setup.bash" >> /home/$USERNAME/.bashrc \
    && echo "export ROS_DOMAIN_ID=30 #TURTLEBOT3" >> /home/$USERNAME/.bashrc \
    && echo "export TURTLEBOT3_MODEL=waffle_pi" >> /home/$USERNAME/.bashrc \
    && echo "export LDS_MODEL=LDS_01" >> /home/$USERNAME/.bashrc

COPY ./docker/entrypoint.sh /
ENTRYPOINT [ "/entrypoint.sh" ]

# RUN echo "\n\
# export TURTLEBOT3_MODEL=waffle_pi" >> ~/.bashrc
 
# Set the working folder at startup
WORKDIR $HOME/turtlebot3_ws